# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(default=0)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=200)),
                ('isxf', models.BooleanField(default=False)),
                ('pmdesc', models.CharField(max_length=100)),
                ('specifics', models.CharField(max_length=100)),
                ('prices', models.FloatField(default=0)),
                ('marketprice', models.FloatField(default=0)),
                ('categoryid', models.IntegerField(default=0)),
                ('childcid', models.IntegerField(default=0)),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.IntegerField(default=0)),
                ('storenums', models.IntegerField(default=0)),
                ('productnum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
