# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='prices',
            new_name='price',
        ),
    ]
