# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwheel',
            name='img',
            field=models.CharField(db_column='img', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainwheel',
            name='name',
            field=models.CharField(db_column='name', max_length=64),
        ),
        migrations.AlterField(
            model_name='mainwheel',
            name='trackid',
            field=models.IntegerField(db_column='trackid', default=1),
        ),
    ]
