# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0007_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=50),
        ),
    ]
