# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0008_auto_20200310_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productimg',
            field=models.CharField(max_length=256),
        ),
    ]
