# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0009_auto_20200310_2127'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['marketprice'], name='axf_goods_marketp_e5e84f_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['childcid'], name='axf_goods_childci_0848cc_idx'),
        ),
    ]
