# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-11 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0010_auto_20200311_1306'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goods',
            name='axf_goods_marketp_e5e84f_idx',
        ),
        migrations.RemoveIndex(
            model_name='goods',
            name='axf_goods_childci_0848cc_idx',
        ),
    ]
