# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0012_axfuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_email',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
