# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0013_auto_20200312_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_num', models.IntegerField(default=1)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXP.Goods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXP.AXFUser')),
            ],
            options={
                'db_table': 'Order_cart',
            },
        ),
        migrations.CreateModel(
            name='Order_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_num', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXP.Goods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXP.AXFUser')),
            ],
            options={
                'db_table': 'Order_record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='order_record',
            unique_together=set([('good_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='order_cart',
            unique_together=set([('good_id', 'user_id')]),
        ),
    ]
