# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0014_auto_20200319_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_record',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
