# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0015_order_record_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_record',
            name='order_num',
            field=models.CharField(max_length=128),
        ),
    ]
