# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0016_auto_20200319_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_record',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
