# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXP', '0017_order_record_creat_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_record',
            unique_together=set([('good_id', 'user_id', 'order_num')]),
        ),
    ]
